% By Willi Mutschler, September 26, 2016. Email: willi@mutschler.eu
function X1 = GetKronMom3(X0,E_A,E_B,E_C,E_AB,E_AC,E_BC)
    % Get noncentral Kronecker Moments E[kron(A,B,C)] from central Kronecker Moments E[kron(A-E(A),B-E(B),C-E(C))]
    Kba = commutation(size(E_B,1),size(E_A,1));
    Kba_Ic = kron(Kba,eye(size(E_C,1)));
    X1 = X0...
        + kron(E_AB,E_C)...
        + kron(E_A,E_BC)...
        + Kba_Ic*kron(E_B,E_AC)...
        - 2*kron(E_A,kron(E_B,E_C));
end