% By Willi Mutschler, September 26, 2016. Email: willi@mutschler.eu
function X1 = GetKronMom4(X0,E_A,E_B,E_C,E_D,E_AB,E_AC,E_AD,E_BC, E_BD, E_CD, E_ABC, E_ABD, E_ACD, E_BCD)
% Get noncentral Kronecker Moments E[kron(A,B,C,D)] from central Kronecker Moments E[kron(A-E(A),B-E(B),C-E(C),D-E(D))]
Kba = commutation(size(E_B,1),size(E_A,1));
Kcb = commutation(size(E_C,1),size(E_B,1));
Kdc = commutation(size(E_D,1),size(E_C,1));
Ia = eye(size(E_A,1));
Id = eye(size(E_D,1));
Iab = eye(size(E_A,1)*size(E_B,1));
Icd = eye(size(E_C,1)*size(E_D,1));
    
    X1 = X0...
        + kron(Iab,Kdc)*kron(E_ABD,E_C)...
        + kron(E_A,E_BCD)...
        + kron(Kba,Icd)*kron(E_B,E_ACD)...
        + kron(E_ABC,E_D)...
        - kron(Ia,kron(Kcb,Id))*kron(E_A,kron(E_C,E_BD))...
        - kron(Kba,Kdc)*kron(E_B,kron(E_AD,E_C))...
        - kron(E_A,kron(E_B,E_CD))...
        - kron(E_AB,kron(E_C,E_D))...
        - kron(E_A,kron(E_BC,E_D))...
        - kron(Kba,Icd)*kron(E_B,kron(E_AC,E_D))...
        +3*kron(E_A,kron(E_B,kron(E_C,E_D)));    
    
end