function outcell=parse_sizevec(sz,numargsout,dim)
%For Imitating the argument processing behaviour of the size() function
%
%SZ - the vector of size coordinates generated by calling routine
%


extraargsin=isvar('dim');



if extraargsin,

  if ~isnum(dim), error('DIM argument must be scalar.'); end
  
  if dim>length(sz), sz(end+1:dim)=1; end
  
  sz=sz(dim);

end


if numargsout<=1,

    outcell{1}=sz;
    return;

elseif extraargsin,

  error('When DIM argument specified, one output arg allowed.')

else

 
  if length(sz)>=numargsout

    sz(numargsout)=prod(sz(numargsout:end));
    sz(numargsout+1:end)=[];
    
  else
    
    sz(end+1:numargsout)=1;  
      
  end

  outcell=encell(sz);

end

